export default [
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
  {
    'name': 'Singularity',
    'artist': 'Jon Hopkins',
    'number': '50',
    'imageName': 'singularity',
    'songTitles': [
      "Singularity",
      "Emerald Rush",
      "Neon Pattern Drum",
      "Everything Connected",
      "Feel First Life",
      "C O S M",
      "Echo Dissolve",
      "Luminous Beings",
      "Recovery",
    ],
    'genre': 'Electronic',
    'spotifyUrl': 'https://open.spotify.com/album/1nvzBC1M3dlCMIxfUCBhlO?si=D1BmqyiySLGZSqT7dvuxyg'
  },
]
